import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <ClerkProvider>
      <Header />
      <main>
        {children}
      </main>

      <SanityLive />
      <Footer/>
    </ClerkProvider> 
  );
}
